addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"  % "0.8.2")
addSbtPlugin("org.scalariform"  % "sbt-scalariform"       % "1.6.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.1.10")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"       % "1.2.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"               % "0.8.5")
addSbtPlugin("me.lessis"        % "bintray-sbt"           % "0.3.0")
